@SecretVault_HostAddress = http://localhost:5204

  
// captura token
POST {{SecretVault_HostAddress}}/login
Content-Type: application/json

{
"username":"admin",
"password":"3CB4B692CDAE4539AAE29CA5F2C90918"
}
### cria usuarios

POST {{SecretVault_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzE5MjU4NjgyLCJleHAiOjE3MTkyNjIyODIsImlhdCI6MTcxOTI1ODY4Mn0.c1NMcJwPGWxTyZcH_JUCZpdyjFqoI5Ob8UTU-Xc4ZAc

{
"username": "testeUsr",
"password" : "3CB4B692CDAE4539AAE29CA5F2C90888",
"role": "operator"
}

### Lista usuários
GET {{SecretVault_HostAddress}}/getusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzE5MjU4NjgyLCJleHAiOjE3MTkyNjIyODIsImlhdCI6MTcxOTI1ODY4Mn0.c1NMcJwPGWxTyZcH_JUCZpdyjFqoI5Ob8UTU-Xc4ZAc

### Cria secredo
POST {{SecretVault_HostAddress}}/secrets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzE5MjU4NjgyLCJleHAiOjE3MTkyNjIyODIsImlhdCI6MTcxOTI1ODY4Mn0.c1NMcJwPGWxTyZcH_JUCZpdyjFqoI5Ob8UTU-Xc4ZAc

{
  "key": "MyDb",
  "encryptedValue": "Server=xx.x.x.x;Port=3306;Database=meubanco;Uid=meuId;Pwd=minhasenha;SslMode=none;"
}

### Captura segredos
GET {{SecretVault_HostAddress}}/secrets/MyDb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzE5MjU4NjgyLCJleHAiOjE3MTkyNjIyODIsImlhdCI6MTcxOTI1ODY4Mn0.c1NMcJwPGWxTyZcH_JUCZpdyjFqoI5Ob8UTU-Xc4ZAc


### Lista segredos
GET {{SecretVault_HostAddress}}/getsecrets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzE5MjU4NjgyLCJleHAiOjE3MTkyNjIyODIsImlhdCI6MTcxOTI1ODY4Mn0.c1NMcJwPGWxTyZcH_JUCZpdyjFqoI5Ob8UTU-Xc4ZAc

### Encripta um valor
POST {{SecretVault_HostAddress}}/configure/encrypt/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzE5MjU4NjgyLCJleHAiOjE3MTkyNjIyODIsImlhdCI6MTcxOTI1ODY4Mn0.c1NMcJwPGWxTyZcH_JUCZpdyjFqoI5Ob8UTU-Xc4ZAc
{
"plainText":"pfhmmlQDAjPvSwlohDU9HFR1RyUSsqx3"

}

